<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>klexir</AssemblyName>
    <RootNamespace>Klexir.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Klexir.Lang\Klexir.Lang.csproj" />
  </ItemGroup>

</Project>
